### ISSUE TITLE
ode_test: "error: code too large"

### ISSUE THREAD

**Issue by mewmew** [quixotic-cynic/open-diablo-editor#3]
Hi Matthew,

I ran into this error when trying to compile the test cases for ODE.

```
[~/Desktop/open-diablo-editor/OpenDiabloEditor/src/uk/me/karlsen/ode_test]$ javac -classpath /usr/share/java/junit.jar -sourcepath ~/Desktop/open-diablo-editor/OpenDiabloEditor/src/ *.java
TestBaseMonster.java:14: error: code too large
public class TestBaseMonster extends TestCase {
       ^
1 error
```

Are you able to compile this file? If so, what compiler and which command line options are you using?

Cheers /u

**Comment by quixotic-cynic** [comment]
Hi /u,

Probably not worth building at the moment since the changes I have
made so far are small (more this weekend)!

However, than you very much for pointing out the issue -- clearly
it needs to be fixed or resolved somehow.

I'm running the program in Eclipse using Zulu 8.9.0.4 (on Windows)
using the default parameters.

Assuming you are using OpenJDK on Ubuntu or something similar, I can
test that and will do so tomorrow... not right now... I need sleep! ;)

Thanks & regards,
Matthew

**Comment by mewmew** [comment]
> Probably not worth building at the moment since the changes I have made so far are small (more this weekend)!

Ok. Thanks for the heads up! Send me a ping later : )

**Comment by mewmew** [comment]
Hi Matthew,

How are you and how have you been?

I was wondering if you've had a chance to play with ODE any recently. I still get the "code too large" error when compiling the test cases at revision 38a61350ba454c6161c727657dc65c6724f8515d.

Hope you've had a great spring so far, and enjoy the return of the sun! Here in Sweden it was snowing the other day : )

Cheers /u

**Comment by quixotic-cynic** [comment]
Hi /u,

Thanks for the reminder about ODE. Just committed a substantial code change. Sorry that I have not had a chance to look at this issue yet. I will test on Linux and get back to you today.

I'll also send an e-mail later.

Thanks & regards,
QC / Matthew

**Comment by quixotic-cynic** [comment]
OK. After a bit of searching it seems that the "code too large" error relates to the ridiculously big shorthand arrays that I put in the java test files. Since these bytes are from the Diablo exe I don't think we should store them in the source files and I am thus modifying the tests to remove all traces of these byte arrays. I suspect it is really bad practice to have arrays of this size "hard coded" anyway...

**Comment by quixotic-cynic** [comment]
Right. Tests should be fixed /u. Hope you have no more problems. Please let me know it is OK if/when you check it and I will close the issue. Thanks, QC / Matthew

**Comment by mewmew** [comment]
Lovely!

The tests are working now.

```
u@x1 ~/D/o/O/src> java -classpath .:/usr/share/java/junit.jar:/usr/share/java/hamcrest-core.jar org.junit.runner.JUnitCore uk.me.karlsen.ode.test.{TestBaseItem,TestBaseMonster,TestCharacterStore,TestItemModifier,TestQuest,TestShrinesStore,TestSpell,TestUniqueItem,TestUniqueMonster}

JUnit version 4.12
...............
Time: 1.553

OK (15 tests)
```

You can close this issue now :) Thanks!
